/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 但是您可以手动创建侧边栏
  notes: [{ type: 'autogenerated', dirName: '学习笔记' }],
  webBase: [{ type: 'autogenerated', dirName: '前端基础' }],
  fragmentation: [{ type: 'autogenerated', dirName: '碎片化' }]
};

module.exports = sidebars;
